select t_itemList.*,
       tex_TextureType,
       tex_TexturePath,
       rs_RelationshipType,
       rs_RelationshipItemID,
       rs_RelationshipQuantity,
       rs_RelationshipWeight,
       df_Energy,
       df_Happiness,
       dfm_PetTypeID,
       dfm_Energy,
       dfm_Happiness,
       fm_FishName,
       fm_SpawnChanceModifier,
       cat_CategoryID,
       cat_CategoryName,
       bp_CoinCost,
       bp_ShardCost,
       bp_ResultItemID,
       bp_ResultItemTier,
       bpi_IngredientID,
       bpi_InItemID,
       bpi_InCategoryID,
       bpi_InItemRarity,
       bpi_InItemTier,
       bpi_InQuantity,
       am_AvatarModifierType,
       am_ModifierValue,
       ss_StatType,
       ss_StatValue,
       ps_StatType,
       ps_Tier,
       ps_StartRange,
       ps_EndRange,
       fs_ItemStateID,
       fs_Order,
       fs_Transition,
       fs_MinAge,
       fs_ConsumableItemID,
       fs_ConsumableAmount,
       fs_SpeedUpItemID,
       fs_SpeedUpResultStateIndex,
       fs_ExpireDuration,
       fs_ExpiredStateIndex
from (
         select ItemID                    as si_ItemID,
                ItemRarity                as il_ItemRarity,
                ItemName                  as il_ItemName,
                ItemNamePlural            as il_ItemNamePlural,
                Description               as il_Description,
                Cost                      as il_Cost,
                CashCost                  as il_CashCost,
                SaleFactor                as il_SaleFactor,
                SaleShardCount            as il_SaleShardCount,
                StoreItemTier             as il_StoreItemTier,
                InventoryMax              as il_InventoryMax,
                IsParentItem              as il_IsParentItem,
                Uses                      as il_Uses,
                CreativePoints            as il_CreativePoints,
                RewardTypeID              as il_RewardTypeID,
                Points                    as il_Points,
                RankID                    as il_RankID,
                IconName                  as il_IconName,
                AssetName                 as il_AssetName,
                ActionDB                  as il_ActionDB,
                ActionDBImage             as il_ActionDBImage,
                WeaponName                as il_WeaponName,
                Movie                     as il_Movie,
                Geometry2                 as il_Geometry2,
                HasToggleWings            as il_HasToggleWings,
                PartBone2                 as il_PartBone2,
                Gender                    as il_Gender,
                PetTypeID                 as il_PetTypeID,
                PetStage                  as il_PetStage,
                PetToyType                as il_PetToyType,
                IsNew                     as il_IsNew,
                Is2D                      as il_Is2D,
                StorePreviewImage         as il_StorePreviewImage,
                StorePreviewScale         as il_StorePreviewScale,
                GlowColor                 as il_GlowColor,
                EffectDuration            as il_EffectDuration,
                StableNestCount           as il_StableNestCount,
                HappinessDecreaseModifier as il_HappinessDecreaseModifier
         from Item_ItemList
     ) as t_itemList
         LEFT JOIN
     (
         select ItemID      as si_ItemID,
                TextureType as tex_TextureType,
                TexturePath as tex_TexturePath,
                null        as rs_RelationshipType,
                null        as rs_RelationshipItemID,
                null        as rs_RelationshipQuantity,
                null        as rs_RelationshipWeight,
                null        as df_Energy,
                null        as df_Happiness,
                null        as dfm_PetTypeID,
                null        as dfm_Energy,
                null        as dfm_Happiness,
                null        as fm_FishName,
                null        as fm_SpawnChanceModifier,
                null        as cat_CategoryID,
                null        as cat_CategoryName,
                null        as bp_CoinCost,
                null        as bp_ShardCost,
                null        as bp_ResultItemID,
                null        as bp_ResultItemTier,
                null        as bpi_IngredientID,
                null        as bpi_InItemID,
                null        as bpi_InCategoryID,
                null        as bpi_InItemRarity,
                null        as bpi_InItemTier,
                null        as bpi_InQuantity,
                null        as am_AvatarModifierType,
                null        as am_ModifierValue,
                null        as ss_StatType,
                null        as ss_StatValue,
                null        as ps_StatType,
                null        as ps_Tier,
                null        as ps_StartRange,
                null        as ps_EndRange,
                null        as fs_ItemStateID,
                null        as fs_Order,
                null        as fs_Transition,
                null        as fs_MinAge,
                null        as fs_ConsumableItemID,
                null        as fs_ConsumableAmount,
                null        as fs_SpeedUpItemID,
                null        as fs_SpeedUpResultStateIndex,
                null        as fs_ExpireDuration,
                null        as fs_ExpiredStateIndex
         from Item_Textures as t_tex
         UNION ALL
         select ItemID               as si_ItemID,
                null                 as tex_TextureType,
                null                 as tex_TexturePath,
                RelationshipType     as rs_RelationshipType,
                RelationshipItemID   as rs_RelationshipItemID,
                RelationshipQuantity as rs_RelationshipQuantity,
                RelationshipWeight   as rs_RelationshipWeight,
                null                 as df_Energy,
                null                 as df_Happiness,
                null                 as dfm_PetTypeID,
                null                 as dfm_Energy,
                null                 as dfm_Happiness,
                null                 as fm_FishName,
                null                 as fm_SpawnChanceModifier,
                null                 as cat_CategoryID,
                null                 as cat_CategoryName,
                null                 as bp_CoinCost,
                null                 as bp_ShardCost,
                null                 as bp_ResultItemID,
                null                 as bp_ResultItemTier,
                null                 as bpi_IngredientID,
                null                 as bpi_InItemID,
                null                 as bpi_InCategoryID,
                null                 as bpi_InItemRarity,
                null                 as bpi_InItemTier,
                null                 as bpi_InQuantity,
                null                 as am_AvatarModifierType,
                null                 as am_ModifierValue,
                null                 as ss_StatType,
                null                 as ss_StatValue,
                null                 as ps_StatType,
                null                 as ps_Tier,
                null                 as ps_StartRange,
                null                 as ps_EndRange,
                null                 as fs_ItemStateID,
                null                 as fs_Order,
                null                 as fs_Transition,
                null                 as fs_MinAge,
                null                 as fs_ConsumableItemID,
                null                 as fs_ConsumableAmount,
                null                 as fs_SpeedUpItemID,
                null                 as fs_SpeedUpResultStateIndex,
                null                 as fs_ExpireDuration,
                null                 as fs_ExpiredStateIndex
         from Item_Relationships as t_rs
         UNION ALL
         select t_df.si_ItemID,
                null as tex_TextureType,
                null as tex_TexturePath,
                null as rs_RelationshipType,
                null as rs_RelationshipItemID,
                null as rs_RelationshipQuantity,
                null as rs_RelationshipWeight,
                df_Energy,
                df_Happiness,
                dfm_PetTypeID,
                dfm_Energy,
                dfm_Happiness,
                null as fm_FishName,
                null as fm_SpawnChanceModifier,
                null as cat_CategoryID,
                null as cat_CategoryName,
                null as bp_CoinCost,
                null as bp_ShardCost,
                null as bp_ResultItemID,
                null as bp_ResultItemTier,
                null as bpi_IngredientID,
                null as bpi_InItemID,
                null as bpi_InCategoryID,
                null as bpi_InItemRarity,
                null as bpi_InItemTier,
                null as bpi_InQuantity,
                null as am_AvatarModifierType,
                null as am_ModifierValue,
                null as ss_StatType,
                null as ss_StatValue,
                null as ps_StatType,
                null as ps_Tier,
                null as ps_StartRange,
                null as ps_EndRange,
                null as fs_ItemStateID,
                null as fs_Order,
                null as fs_Transition,
                null as fs_MinAge,
                null as fs_ConsumableItemID,
                null as fs_ConsumableAmount,
                null as fs_SpeedUpItemID,
                null as fs_SpeedUpResultStateIndex,
                null as fs_ExpireDuration,
                null as fs_ExpiredStateIndex
         from (
                  select ItemID    as si_ItemID,
                         Energy    as df_Energy,
                         Happiness as df_Happiness
                  from Item_DragonFood
              ) as t_df
                  LEFT JOIN
              (
                  select ItemID    as si_ItemID,
                         PetTypeID as dfm_PetTypeID,
                         Energy    as dfm_Energy,
                         Happiness as dfm_Happiness
                  from Item_DragonFood_Modifier
              ) as t_dfm
              ON t_df.si_ItemID = t_dfm.si_ItemID
         UNION ALL
         select ItemID              as si_ItemID,
                null                as tex_TextureType,
                null                as tex_TexturePath,
                null                as rs_RelationshipType,
                null                as rs_RelationshipItemID,
                null                as rs_RelationshipQuantity,
                null                as rs_RelationshipWeight,
                null                as df_Energy,
                null                as df_Happiness,
                null                as dfm_PetTypeID,
                null                as dfm_Energy,
                null                as dfm_Happiness,
                FishName            as fm_FishName,
                SpawnChanceModifier as fm_SpawnChanceModifier,
                null                as cat_CategoryID,
                null                as cat_CategoryName,
                null                as bp_CoinCost,
                null                as bp_ShardCost,
                null                as bp_ResultItemID,
                null                as bp_ResultItemTier,
                null                as bpi_IngredientID,
                null                as bpi_InItemID,
                null                as bpi_InCategoryID,
                null                as bpi_InItemRarity,
                null                as bpi_InItemTier,
                null                as bpi_InQuantity,
                null                as am_AvatarModifierType,
                null                as am_ModifierValue,
                null                as ss_StatType,
                null                as ss_StatValue,
                null                as ps_StatType,
                null                as ps_Tier,
                null                as ps_StartRange,
                null                as ps_EndRange,
                null                as fs_ItemStateID,
                null                as fs_Order,
                null                as fs_Transition,
                null                as fs_MinAge,
                null                as fs_ConsumableItemID,
                null                as fs_ConsumableAmount,
                null                as fs_SpeedUpItemID,
                null                as fs_SpeedUpResultStateIndex,
                null                as fs_ExpireDuration,
                null                as fs_ExpiredStateIndex
         from Item_FishModifiers as t_fm
         UNION ALL
         select si_ItemID,
                null as tex_TextureType,
                null as tex_TexturePath,
                null as rs_RelationshipType,
                null as rs_RelationshipItemID,
                null as rs_RelationshipQuantity,
                null as rs_RelationshipWeight,
                null as df_Energy,
                null as df_Happiness,
                null as dfm_PetTypeID,
                null as dfm_Energy,
                null as dfm_Happiness,
                null as fm_FishName,
                null as fm_SpawnChanceModifier,
                t_cat.cat_CategoryID,
                cat_CategoryName,
                null as bp_CoinCost,
                null as bp_ShardCost,
                null as bp_ResultItemID,
                null as bp_ResultItemTier,
                null as bpi_IngredientID,
                null as bpi_InItemID,
                null as bpi_InCategoryID,
                null as bpi_InItemRarity,
                null as bpi_InItemTier,
                null as bpi_InQuantity,
                null as am_AvatarModifierType,
                null as am_ModifierValue,
                null as ss_StatType,
                null as ss_StatValue,
                null as ps_StatType,
                null as ps_Tier,
                null as ps_StartRange,
                null as ps_EndRange,
                null as fs_ItemStateID,
                null as fs_Order,
                null as fs_Transition,
                null as fs_MinAge,
                null as fs_ConsumableItemID,
                null as fs_ConsumableAmount,
                null as fs_SpeedUpItemID,
                null as fs_SpeedUpResultStateIndex,
                null as fs_ExpireDuration,
                null as fs_ExpiredStateIndex
         from (
                  select ItemID     as si_ItemID,
                         CategoryID as cat_CategoryID
                  from Item_Categories
              ) as t_cat
                  LEFT JOIN
              (
                  select ID           as cat_CategoryID,
                         CategoryName as cat_CategoryName
                  from Item_CategoryList
              ) as t_catList
              ON t_cat.cat_CategoryID = t_catList.cat_CategoryID
         UNION ALL
         select t_bp.si_ItemID,
                null as tex_TextureType,
                null as tex_TexturePath,
                null as rs_RelationshipType,
                null as rs_RelationshipItemID,
                null as rs_RelationshipQuantity,
                null as rs_RelationshipWeight,
                null as df_Energy,
                null as df_Happiness,
                null as dfm_PetTypeID,
                null as dfm_Energy,
                null as dfm_Happiness,
                null as fm_FishName,
                null as fm_SpawnChanceModifier,
                null as cat_CategoryID,
                null as cat_CategoryName,
                bp_CoinCost,
                bp_ShardCost,
                bp_ResultItemID,
                bp_ResultItemTier,
                bpi_IngredientID,
                bpi_InItemID,
                bpi_InCategoryID,
                bpi_InItemRarity,
                bpi_InItemTier,
                bpi_InQuantity,
                null as am_AvatarModifierType,
                null as am_ModifierValue,
                null as ss_StatType,
                null as ss_StatValue,
                null as ps_StatType,
                null as ps_Tier,
                null as ps_StartRange,
                null as ps_EndRange,
                null as fs_ItemStateID,
                null as fs_Order,
                null as fs_Transition,
                null as fs_MinAge,
                null as fs_ConsumableItemID,
                null as fs_ConsumableAmount,
                null as fs_SpeedUpItemID,
                null as fs_SpeedUpResultStateIndex,
                null as fs_ExpireDuration,
                null as fs_ExpiredStateIndex
         from (
                  select ItemID         as si_ItemID,
                         CoinCost       as bp_CoinCost,
                         ShardCost      as bp_ShardCost,
                         ResultItemID   as bp_ResultItemID,
                         ResultItemTier as bp_ResultItemTier
                  from Item_Blueprints
              ) as t_bp
                  LEFT JOIN
              (
                  select ItemID       as si_ItemID,
                         IngredientID as bpi_IngredientID,
                         InItemID     as bpi_InItemID,
                         InCategoryID as bpi_InCategoryID,
                         InItemRarity as bpi_InItemRarity,
                         InItemTier   as bpi_InItemTier,
                         InQuantity   as bpi_InQuantity
                  from Item_Blueprint_Ingredients
              ) as t_bpi
              ON t_bp.si_ItemID = t_bpi.si_ItemID
         UNION ALL
         select ItemID             as si_ItemID,
                null               as tex_TextureType,
                null               as tex_TexturePath,
                null               as rs_RelationshipType,
                null               as rs_RelationshipItemID,
                null               as rs_RelationshipQuantity,
                null               as rs_RelationshipWeight,
                null               as df_Energy,
                null               as df_Happiness,
                null               as dfm_PetTypeID,
                null               as dfm_Energy,
                null               as dfm_Happiness,
                null               as fm_FishName,
                null               as fm_SpawnChanceModifier,
                null               as cat_CategoryID,
                null               as cat_CategoryName,
                null               as bp_CoinCost,
                null               as bp_ShardCost,
                null               as bp_ResultItemID,
                null               as bp_ResultItemTier,
                null               as bpi_IngredientID,
                null               as bpi_InItemID,
                null               as bpi_InCategoryID,
                null               as bpi_InItemRarity,
                null               as bpi_InItemTier,
                null               as bpi_InQuantity,
                AvatarModifierType as am_AvatarModifierType,
                ModifierValue      as am_ModifierValue,
                null               as ss_StatType,
                null               as ss_StatValue,
                null               as ps_StatType,
                null               as ps_Tier,
                null               as ps_StartRange,
                null               as ps_EndRange,
                null               as fs_ItemStateID,
                null               as fs_Order,
                null               as fs_Transition,
                null               as fs_MinAge,
                null               as fs_ConsumableItemID,
                null               as fs_ConsumableAmount,
                null               as fs_SpeedUpItemID,
                null               as fs_SpeedUpResultStateIndex,
                null               as fs_ExpireDuration,
                null               as fs_ExpiredStateIndex
         from Item_AvatarModifiers as t_am
         UNION ALL
         select ItemID    as si_ItemID,
                null      as tex_TextureType,
                null      as tex_TexturePath,
                null      as rs_RelationshipType,
                null      as rs_RelationshipItemID,
                null      as rs_RelationshipQuantity,
                null      as rs_RelationshipWeight,
                null      as df_Energy,
                null      as df_Happiness,
                null      as dfm_PetTypeID,
                null      as dfm_Energy,
                null      as dfm_Happiness,
                null      as fm_FishName,
                null      as fm_SpawnChanceModifier,
                null      as cat_CategoryID,
                null      as cat_CategoryName,
                null      as bp_CoinCost,
                null      as bp_ShardCost,
                null      as bp_ResultItemID,
                null      as bp_ResultItemTier,
                null      as bpi_IngredientID,
                null      as bpi_InItemID,
                null      as bpi_InCategoryID,
                null      as bpi_InItemRarity,
                null      as bpi_InItemTier,
                null      as bpi_InQuantity,
                null      as am_AvatarModifierType,
                null      as am_ModifierValue,
                StatType  as ss_StatType,
                StatValue as ss_StatValue,
                null      as ps_StatType,
                null      as ps_Tier,
                null      as ps_StartRange,
                null      as ps_EndRange,
                null      as fs_ItemStateID,
                null      as fs_Order,
                null      as fs_Transition,
                null      as fs_MinAge,
                null      as fs_ConsumableItemID,
                null      as fs_ConsumableAmount,
                null      as fs_SpeedUpItemID,
                null      as fs_SpeedUpResultStateIndex,
                null      as fs_ExpireDuration,
                null      as fs_ExpiredStateIndex
         from Item_StoreStats as t_ss
         UNION ALL
         select ItemID     as si_ItemID,
                null       as tex_TextureType,
                null       as tex_TexturePath,
                null       as rs_RelationshipType,
                null       as rs_RelationshipItemID,
                null       as rs_RelationshipQuantity,
                null       as rs_RelationshipWeight,
                null       as df_Energy,
                null       as df_Happiness,
                null       as dfm_PetTypeID,
                null       as dfm_Energy,
                null       as dfm_Happiness,
                null       as fm_FishName,
                null       as fm_SpawnChanceModifier,
                null       as cat_CategoryID,
                null       as cat_CategoryName,
                null       as bp_CoinCost,
                null       as bp_ShardCost,
                null       as bp_ResultItemID,
                null       as bp_ResultItemTier,
                null       as bpi_IngredientID,
                null       as bpi_InItemID,
                null       as bpi_InCategoryID,
                null       as bpi_InItemRarity,
                null       as bpi_InItemTier,
                null       as bpi_InQuantity,
                null       as am_AvatarModifierType,
                null       as am_ModifierValue,
                null       as ss_StatType,
                null       as ss_StatValue,
                StatType   as ps_StatType,
                Tier       as ps_Tier,
                StartRange as ps_StartRange,
                EndRange   as ps_EndRange,
                null       as fs_ItemStateID,
                null       as fs_Order,
                null       as fs_Transition,
                null       as fs_MinAge,
                null       as fs_ConsumableItemID,
                null       as fs_ConsumableAmount,
                null       as fs_SpeedUpItemID,
                null       as fs_SpeedUpResultStateIndex,
                null       as fs_ExpireDuration,
                null       as fs_ExpiredStateIndex
         from Item_PossibleStats as t_ps
         UNION ALL
         select ItemID                    as si_ItemID,
                null                      as tex_TextureType,
                null                      as tex_TexturePath,
                null                      as rs_RelationshipType,
                null                      as rs_RelationshipItemID,
                null                      as rs_RelationshipQuantity,
                null                      as rs_RelationshipWeight,
                null                      as df_Energy,
                null                      as df_Happiness,
                null                      as dfm_PetTypeID,
                null                      as dfm_Energy,
                null                      as dfm_Happiness,
                null                      as fm_FishName,
                null                      as fm_SpawnChanceModifier,
                null                      as cat_CategoryID,
                null                      as cat_CategoryName,
                null                      as bp_CoinCost,
                null                      as bp_ShardCost,
                null                      as bp_ResultItemID,
                null                      as bp_ResultItemTier,
                null                      as bpi_IngredientID,
                null                      as bpi_InItemID,
                null                      as bpi_InCategoryID,
                null                      as bpi_InItemRarity,
                null                      as bpi_InItemTier,
                null                      as bpi_InQuantity,
                null                      as am_AvatarModifierType,
                null                      as am_ModifierValue,
                null                      as ss_StatType,
                null                      as ss_StatValue,
                null                      as ps_StatType,
                null                      as ps_Tier,
                null                      as ps_StartRange,
                null                      as ps_EndRange,
                ItemStateID               as fs_ItemStateID,
                ItemStateOrderIndex       as fs_Order,
                StateCompletionTransition as fs_Transition,
                StateCompletionMinAge     as fs_MinAge,
                ConsumableItemID          as fs_ConsumableItemID,
                ConsumableAmount          as fs_ConsumableAmount,
                SpeedUpItemID             as fs_SpeedUpItemID,
                SpeedUpResultStateIndex   as fs_SpeedUpResultStateIndex,
                ExpireDuration            as fs_ExpireDuration,
                ExpiredStateIndex         as fs_ExpiredStateIndex
         from Item_FarmStates as t_fs
     ) as t_itemData
     ON t_itemList.si_ItemID = t_itemData.si_ItemID